### PR TITLE
Custom subscription actions

### LINKED ISSUE #9: Add support for generic model subscriptions
Though DCRF doesn't have a standardized way of subscribing to _all_ updates to _any_ instance in a stream, it does offer support for this type of subscription, handing off implementation responsibility to the developer.

It would be nice if dcrf-client could support these types of arbitrary subscriptions, i.e.
 - Send an arbitrary request (e.g. `subscribe_all`, or whatever action name is chosen)
 - Add a dispatch listener, using a selector of the developer's choosing (e.g. `{action: 'update', data: {...}}`)
 - Automatically resubscribe upon reconnection

### LINKED ISSUE #10: Problem running tests
I was looking at making a pull request with a feature I'd like to see in dcrf-client. I started by looking at following the development section from the readme to get tests running. I am running into some minor issues I was able to deal with and one last issue I'm not sure how to work around :

- The readme states to start with `pipenv install`. `pipenv` does not install dev packages by default, which seem to be required to run tests. This could be addressed by directing contributors to `pipenv install --dev`. Not sure what use `dev-packages` are in the context of dcrf-client, is it seperated for example reasons?
- Running `npm run test` next as in the readme doesn't work because py.test is not in the path yet. `pipenv shell` needs to be run first or instead run `pipenv run npm run test`.
- Running `npm run test` in a pipenv shell for python 3.7 doesn't work with a traceback of
  ```
  > dcrf-client@0.3.0 test:integration /home/joel/WebstormProjects/dcrf-client
  > py.test || true

  Traceback (most recent call last):
    File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/bin/py.test", line 5, in <module>
      from pytest import console_main
    File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/pytest/__init__.py", line 3, in   <module>
      from . import collect
    File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/pytest/collect.py", line 8, in   <module>
      from _pytest.deprecated import PYTEST_COLLECT_MODULE
    File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/_pytest/deprecated.py", line 11,   in <module>
      from _pytest.warning_types import PytestDeprecationWarning
    File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/_pytest/warning_types.py", line 7, in <module>
      from _pytest.compat import final
    File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/_pytest/compat.py", line 57, in   <module>
      import importlib_metadata  # noqa: F401
  ModuleNotFoundError: No module named 'importlib_metadata'
  ```
  
  This seems related to this pytest issue: https://github.com/pytest-dev/pytest/issues/7114. The resolution seems to be to regenerate the `Pipfile.lock` per: https://github.com/pytest-dev/pytest/issues/7114#issuecomment-641822774. I did this using `pipenv lock; pipenv install --dev`.
- At this point, the unit tests now run for me, but there is an issue I'm not familiar with running the integration tests. Is it possible a `pytest` version that is too new is specified in the `Pipfile.lock` file?
  ```
  (dcrf-client-CumnqgWw) [joel@adamant dcrf-client]$ npm run test:integration
  > > dcrf-client@0.3.0 test:integration /home/joel/WebstormProjects/dcrf-client
  > py.test || true

  =================================================================================== test session starts ====================================================================================
  platform linux -- Python 3.7.9, pytest-6.2.1, py-1.10.0, pluggy-0.13.1 -- /home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/bin/python3
  cachedir: .pytest_cache
  django: settings: dcrf_client_test.settings (from ini)
  rootdir: /home/joel/WebstormProjects/dcrf-client, configfile: pytest.ini
  plugins: django-4.1.0, pythonpath-0.7.3
  collecting ... Using selector: EpollSelector
  Expecting event from Mocha of type(s): collect
  Read event from Mocha: {'type': 'collect', 'tests': [{'title': 'returns created values', 'parents': ['DCRFClient', 'things', 'create', 'returns created values'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'imbues retrieve with data', 'parents': ['DCRFClient', 'things', 'create', 'imbues retrieve with data'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'returns empty set', 'parents': ['DCRFClient', 'things', 'list', 'returns empty set'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'returns created rows', 'parents': ['DCRFClient', 'things', 'list', 'returns created rows'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'invokes callback on change', 'parents': ['DCRFClient', 'things', 'subscribe', 'invokes callback on change'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'invokes callback on delete', 'parents': ['DCRFClient', 'things', 'subscribe', 'invokes callback on delete'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'returns created values', 'parents': ['DCRFClient', 'things_with_id', 'create', 'returns created values'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'imbues retrieve with data', 'parents': ['DCRFClient', 'things_with_id', 'create', 'imbues retrieve with data'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'returns empty set', 'parents': ['DCRFClient', 'things_with_id', 'list', 'returns empty set'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'returns created rows', 'parents': ['DCRFClient', 'things_with_id', 'list', 'returns created rows'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'invokes callback on change', 'parents': ['DCRFClient', 'things_with_id', 'subscribe', 'invokes callback on change'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'invokes callback on delete', 'parents': ['DCRFClient', 'things_with_id', 'subscribe', 'invokes callback on delete'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}]}
  INTERNALERROR> Traceback (most recent call last):
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/_pytest/main.py", line 269, in wrap_session
  INTERNALERROR>     session.exitstatus = doit(config, session) or 0
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/_pytest/main.py", line 322, in _main
  INTERNALERROR>     config.hook.pytest_collection(session=session)
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
  INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
  INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
  INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
  INTERNALERROR>     return outcome.get_result()
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
  INTERNALERROR>     raise ex[1].with_traceback(ex[2])
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
  INTERNALERROR>     res = hook_impl.function(*args)
  INTERNALERROR>   File "/home/joel/WebstormProjects/dcrf-client/test/integration/tests/mocha.py", line 179, in pytest_collection
  INTERNALERROR>     session=session,
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/_pytest/nodes.py", line 91, in __call__
  INTERNALERROR>     fail(msg, pytrace=False)
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/_pytest/outcomes.py", line 153, in fail
  INTERNALERROR>     raise Failed(msg=msg, pytrace=pytrace)
  INTERNALERROR> Failed: Direct construction of MochaFile has been deprecated, please use MochaFile.from_parent.
  INTERNALERROR> See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.

  ================================================================================== no tests ran in 0.00s ===================================================================================
  sys:1: ResourceWarning: unclosed file <_io.BufferedWriter name=15>
  sys:1: ResourceWarning: unclosed file <_io.BufferedReader name=16>
  (dcrf-client-CumnqgWw) [joel@adamant dcrf-client]$
  ```

### PR DESCRIPTION
**Pull request by theY4Kman**
This PR is intended to supersede #11, and builds atop the wonderful (and for many months, thankless) contributions from @jhillacre

Fixes #10
Closes #9 

# Brief

This PR adds support for custom subscription actions through `.subscribe()`, and changes `SubscriptionPromise.cancel()`, `.close()`, and `.unsubscribeAll()` to return Promises that resolve upon completion.

Also, this PR switches logging from loglevel to winston, because it offered the configurability I wasn't finding from loglevel.

# Description

## subscribe()
To support custom subscription actions, the prototype for `subscribe()` has been modified. It now accepts an `options` object, allowing `subscribeAction: 'my_custom_subscribe'` and `unsubscribeAction: 'my_custom_unsubscribe'` to be passed. `includeCreateEvents: true` may also be passed in options, instructing the client to also listen for `"action": "create"` events over the wire. Additionally, an arbitrary object may be passed in place of `pk`, enabling custom arguments to be passed to the action.

```ts
/**
 * Subscribe to update and delete events for an object, or perform a custom subscription
 *
 * @param stream Name of object's type stream
 * @param args Identifying information to be included in subscription request
 * @param callback Function to call with payload on new events
 * @param options Optional object to configure the subscription
 * @param options.requestId Specific request ID to submit with the
 *    subscription/unsubscription request, and which will be included in
 *    responses from DCRF. If not specified, one will be automatically generated.
 * @param options.subscribeAction Name of action used in subscription request.
 *    By default, 'subscribe_instance' is used.
 * @param options.unsubscribeAction Name of action used in unsubscription request.
 *    By default, 'unsubscribe_instance' is used.
 * @param options.includeCreateEvents Whether to listen for creation events,
 *    in addition to updates and deletes. By default, this is false.
 * @return Promise Resolves/rejects when response to subscription request received.
 *    On success, the promise will be resolved with null, or an empty object.
 *    On failure, the promise will be rejected with the entire API response.
 *    This Promise has an additional method, cancel(), which can be called
 *    to cancel the subscription.
 */
subscribe(stream: string, args: object, callback: SubscriptionHandler, options?: SubscribeOptions): CancelablePromise<object | null>;
```

## SubscriptionPromise.cancel() / close() / unsubscribeAll()
These three methods have been changed to return Promises that resolve when their actions are completed. 

Many moons ago, DCRF (or CRF?) didn't support unsubscribing, so no requests were sent to the server upon canceling a subscription — the client would simply ignore those unsubscribed events. However — also many moons ago :sweat_smile: — DCRF added support for unsubscribing, so there grew a good reason for dcrf-client to wait for those unsubscription requests to complete. @jhillacre converted `SubscriptionPromise.cancel()` to a Promise in #11 to cover that case.

In this PR, I've also converted `client.close()` and `client.unsubscribeAll()` to return Promises — though, my main motivation for this was to ensure all subscriptions from one test were cleaned up before the next one ran.

## Logging
I believe the initial reason for switching from [loglevel](https://www.npmjs.com/package/loglevel) to [winston](https://www.npmjs.com/package/winston) was loglevel's lack of argument formatting — there was one place I was doing something like `log.debug('Thing is: %s', thing)` and expecting `Thing is: <thing>`, but actually getting `This is: %s <Thing>`.

Upon switching, I enjoyed the option of including colours to the console, which really helped when debugging the integration tests.

However, **it should be noted that I haven't inspected what the logs look like in a browser!** It may spew too much by default... Or it may be printing nothing. It might be worth adding some ability to configure the log levels to dcrf-client.

## Miscellaneous
TypeScript was upgraded to 3.7+ to gain support for optional chaining (`a?.b?.c` instead of `a && a.b && a.b.c`) and nullish coalescing (`a ?? b` instead of `a == null ? b : a`), because I believe it makes the code more succinct and easier to read.

### CODE REVIEW

**Comment by theY4Kman** [comment]
@jhillacre @pmack — I'd love to know what y'all think of this version in practice. Besides the `includeCreateEvents`, it doesn't seem like a huge lift, but I'm a little concerned about possible annoyances (or shortcomings) with the logging from winston.

With your blessing, though, I'll have this pushed up to npm in the blink of an eye.

Although we kept the arguments for `subscribe()` backwards-compatible, the return types for those few public functions were changed, and by strict semantic versioning rules, a major version bump is warranted. It's a shame I'm not using this opportunity to move the callback/handler arg to the back of the prototype, where it belongs :P

```ts
// Current prototype without chopping down the args

client.subscribe('streeheem', {arg: 1}, (obj, action) => {
	do.a.thing(obj, action);
}, {
	subscribeAction: 'smash_that_subscribe',
	unsubscribeAction: 'vanish',
});

//  I don't like the lack of continuation indents


// Current prototype with chopped args
client.subscribe(
	'streeheem', 
	{arg: 1}, 
	(obj, action) => {
		do.a.thing(obj, action);
	}, 
	{
		subscribeAction: 'smash_that_subscribe',
		unsubscribeAction: 'vanish',
	},
);

// Feels a bit overly spaced... 
// and, of course, the options arg seems out of order.
// Plus, if the handler is long, the options might be overlooked


// I wonder if it may make sense to have `options` and `handler` mutually exclusive,
// such that if `options` are specified, `handler` is one of the properties
client.subscribe('streeheem', {arg: 1}, {
	subscribeAction: 'smash_that_subscribe',
	unsubscribeAction: 'vanish',
	handler(obj, action) {
		do.a.thing(obj, action);
	}
});
```

Just thinkin :P

**Comment by theY4Kman** [comment]
I just added a few more commits to resolve those testing woes from #10. Now, in this PR:
 - The README says to use `pipenv install --dev` to get the deps
 - The `npm run test:integration` now performs `pipenv run py.test`
 - The Python version has been bumped to 3.8 to resolve the weird `importlib_metadata` error (which I _was_ able to reproduce when using pipenv's auto-created virtualenv)

**Comment by jhillacre** [comment]
Handler as option property or as options argument seems reasonable to me.

> Although we kept the arguments for `subscribe()` backwards-compatible, the return types for those few public functions were changed, and by strict semantic versioning rules, a major version bump is warranted. It's a shame I'm not using this opportunity to move the callback/handler arg to the back of the prototype, where it belongs :P

It's early in the project, more major bumps now are good. I always say we aren't running out of version numbers. One thing to help users coming for the journey might be a CHANGES.md, detailing breaking changes.

> I just added a few more commits to resolve those testing woes from #10. Now, in this PR:

> * The README says to use pipenv install --dev to get the deps
> * The npm run test:integration now performs pipenv run py.test
> * The Python version has been bumped to 3.8 to resolve the weird importlib_metadata error (which I was able to reproduce > * when using pipenv's auto-created virtualenv)

I can confirm that the tests work for me on the new branch. 👍👍

> TypeScript was upgraded to 3.7+ to gain support for optional chaining (a?.b?.c instead of a && a.b && a.b.c) and nullish coalescing (a ?? b instead of a == null ? b : a), because I believe it makes the code more succinct and easier to read.

I needed to blow away my old node_modules to get the build to work. Seemed like the old 'tsc' is used during 'prepare' instead of the new one, but I wasn't able to reproduce by manually installing old 'typescript' versions then reinstalling using `npm install`.

```console
src/index.ts:70:37 - error TS1109: Expression expected.

70     this.pkField = options.pkField ?? 'pk';
                                       ~

src/index.ts:70:43 - error TS1005: ':' expected.

70     this.pkField = options.pkField ?? 'pk';
```

**Comment by theY4Kman** [comment]
Well, I guess I'll save a prototype for the next major version, just to get this out the door quicker.

And good call on a changelog. It shows how long ago I released this project... all my new things _start_ with a CHANGELOG.md. I'll add one now.

**Comment by theY4Kman** [comment]
@jhillacre Alright, version 1.0.0 has been published! https://www.npmjs.com/package/dcrf-client/v/1.0.0

Thanks for all your work, and for spending your own time to update the code _and_ open a PR for it. It's much appreciated, and deserved a much swifter response than you got. Now, let's see if we can't get that pagination going...

With all the stuff I've had to pull to get the integration tests robust, it seems some PRs to DCRF itself are in order for me.

**Pull request merged**
